### ISSUE TITLE
実行ファイルの最初にタイポと思われる`<`がある

### ISSUE THREAD

**Issue by genokamura** [cyber-neko/php_oop_test#1]
複数のファイル内に以下のようなミスが見られます。
https://github.com/cyber-neko/php_oop_test/blob/e70130e4a8ea6e0f5210b0ac89bb5f5df3487271/output/question1.php#L1

**Comment by cyber-neko** [comment]
https://github.com/cyber-neko/php_oop_test/commit/bb36ff2f9e1b577761fb60df325073d2489536e3 で修正したのでクローズします
